karser_recaptcha3:
    site_key: '%env(RECAPTCHA3_KEY)%'
    secret_key: '%env(RECAPTCHA3_SECRET)%'
    score_threshold: 0.5
    enabled: true

when@dev:
    karser_recaptcha3:
        enabled: false


when@test:
    karser_recaptcha3:
        enabled: false
