knpu_oauth2_client:
    clients:
        # configure your clients as described here: https://github.com/knpuniversity/oauth2-client-bundle#configuration
        concept2:
            type: generic
            provider_class: App\OAuth\Concept2Provider
            client_id: '%env(OAUTH_CONCEPT2_ID)%'
            client_secret: '%env(OAUTH_CONCEPT2_SECRET)%'
            redirect_route: oauth_concept2_check
            redirect_params: {}
