framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: '%env(MAILER_SENDER)%'
        headers:
            From: '%env(MAILER_FROM)%'
            Reply-To: '%env(MAILER_REPLY_TO)%'
