# See the configuration reference at https://github.com/scheb/two-factor-bundle/blob/master/Resources/doc/configuration.md
scheb_two_factor:
    security_tokens:
         - Symfony\Component\Security\Guard\Token\PostAuthenticationGuardToken
    email:
        enabled: true
        digits: 6
        mailer: App\Mailer\TwoFactorAuthenticationMailer
        template: security/2fa_form.html.twig
