twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['forms/bootstrap_5_layout.html.twig']
    paths:
        '%kernel.project_dir%/assets/images': images
    globals:
        APP_VERSION: '%env(APP_VERSION)%'

when@test:
    twig:
        strict_variables: true
