twig:
    default_path: '%kernel.project_dir%/templates'
    date:
        format: d/m/Y
        interval_format: '%%d days'
    form_themes:
        - 'bootstrap_5_layout.html.twig'
    paths:
        '%kernel.project_dir%/assets/images': images
    globals:
        APP_VERSION: '%env(APP_VERSION)%'
        APP_IBAN: '%env(APP_IBAN)%'
        APP_BIC: '%env(APP_BIC)%'
        projectDir: '%kernel.project_dir%'

when@test:
    twig:
        strict_variables: true
