twig:
    file_name_pattern: '*.twig'
    form_themes:
        - 'bootstrap_5_layout.html.twig'
        - 'form/_turnstile.html.twig'
        - 'form/_training.html.twig'
    globals:
        treasurer_stamp:  '%treasurer_stamp%'

when@test:
    twig:
        strict_variables: true
