twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['forms/bootstrap_5_layout.html.twig']
    paths:
        '%kernel.project_dir%/assets/images': images
        '%kernel.project_dir%/assets/styles': styles
    globals:
        APP_VERSION: '%env(APP_VERSION)%'
        APP_IBAN: '%env(APP_IBAN)%'
        APP_BIC: '%env(APP_BIC)%'

when@test:
    twig:
        strict_variables: true
