vich_uploader:
    db_driver: orm

    mappings:
        medical_certificate:
#            uri_prefix: /images/products
            upload_destination: '%kernel.project_dir%/protected_files/medical_certificates'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
