framework:
    workflows:
        license:
            type: workflow
            audit_trail:
                enabled: true
            marking_store:
                type: method
            supports:
                - App\Entity\License
            initial_marking: [wait_medical_certificate_validation, wait_payment_validation]
            places:
                wait_medical_certificate_validation:
                    metadata:
                        title: Attente de validation du certificat
                        badge: warning
                medical_certificate_validated:
                    metadata:
                        title: Certificat médical validé
                        badge: success
                medical_certificate_rejected:
                    metadata:
                        title: Certificat médical invalide
                        badge: danger
                wait_payment_validation:
                    metadata:
                        title: Attente de validation du paiement
                        badge: warning
                payment_validated:
                    metadata:
                        title: Paiement validé
                        badge: success
                validated:
                    metadata:
                        title: Validée
                        badge: success
            transitions:
                validate_medical_certificate:
                    from: wait_medical_certificate_validation
                    to:   medical_certificate_validated
                    metadata:
                        title: Valider le certificat médical
                        button: primary
                reject_medical_certificate:
                    from: wait_medical_certificate_validation
                    to: medical_certificate_rejected
                    metadata:
                        title: Rejeter le certificat médical
                        button: warning
                unreject_medical_certificate:
                    from: medical_certificate_rejected
                    to:   wait_medical_certificate_validation
                    metadata:
                        title: Passer le certificat en attente de validation
                        button: danger
                validate_payment:
                    from: wait_payment_validation
                    to:   payment_validated
                    metadata:
                        title: Valider le paiement
                        button: primary
                validate_license:
                    from:
                        - medical_certificate_validated
                        - payment_validated
                    to:   validated
                    metadata:
                        title: Valider la licence
                        button: primary
