framework:
    workflows:
        license:
            type: workflow
            audit_trail:
                enabled: true
            marking_store:
                type: method
            supports:
                - App\Entity\License
            initial_marking: [wait_medical_certificate_validation, wait_payment_validation]
            places:
                wait_medical_certificate_validation:
                    metadata:
                        title: Attente de validation du certificat
                        badge: warning
                medical_certificate_validated:
                    metadata:
                        title: Certificat médical validé
                        badge: success
                medical_certificate_rejected:
                    metadata:
                        title: Certificat médical invalide
                        badge: danger
                wait_payment_validation:
                    metadata:
                        title: Attente de validation du paiement
                        badge: warning
                payment_validated:
                    metadata:
                        title: Paiement validé
                        badge: success
                validated:
                    metadata:
                        title: Validée
                        badge: success
            transitions:
                validate_medical_certificate:
                    guard: "is_granted('ROLE_SEASON_MEDICAL_CERTIFICATE_ADMIN')"
                    from: wait_medical_certificate_validation
                    to: medical_certificate_validated
                reject_medical_certificate:
                    guard: "is_granted('ROLE_SEASON_MEDICAL_CERTIFICATE_ADMIN')"
                    from: wait_medical_certificate_validation
                    to: medical_certificate_rejected
                unreject_medical_certificate:
                    guard: "is_granted('ROLE_SEASON_MEDICAL_CERTIFICATE_ADMIN')"
                    from: medical_certificate_rejected
                    to: wait_medical_certificate_validation
                validate_payment:
                    guard: "is_granted('ROLE_SEASON_PAYMENTS_ADMIN')"
                    from: wait_payment_validation
                    to: payment_validated
                validate_license:
                    guard: "is_granted('ROLE_SEASON_ADMIN')"
                    from:
                        - medical_certificate_validated
                        - payment_validated
                    to: validated
