version: '3'

services:
###> doctrine/doctrine-bundle ###
    database:
        ports:
          - "127.0.0.1:5432:5432"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
    mailer:
        image: schickling/mailcatcher
        ports:
            - "127.0.0.1:1025:1025"
            - "127.0.0.1:1080:1080"
###< symfony/mailer ###

###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###
