version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432:5432"
###< doctrine/doctrine-bundle ###

  mailcatcher:
    ports:
      - "1025:1025"
      - "1080:1080"
