version: '3'

services:
    database:
        image: postgres:13.2
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: main
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - 5432

    mailcatcher:
        image: schickling/mailcatcher
        ports: [1025, 1080]

volumes:
    pgdata:
        driver: local
