[PHP]
;realpath_cache_size = 4096K
;realpath_cache_ttl = 600
;memory_limit = 128M
post_max_size = 20M
upload_max_filesize = 10M

[Date]
date.timezone = Europe/Paris

[Session]
session.gc_probability = 1
session.gc_divisor = 100

[Assertion]
; Switch whether to compile assertions at all (to have no overhead at run-time)
; -1: Do not compile at all
;  0: Jump over assertion at run-time
;  1: Execute assertions
;zend.assertions = -1
zend.assertions = 1

[opcache]
;opcache.enabled = 1
;opcache.memory_consumption = 128
;opcache.max_accelerated_files = 20000
;opcache.validate_timestamps = 0
;opcache.preload = /path/to/project/config/preload.php
;opcache.preload_user = www-data
