name: Continuous Integration
on:
  push:
    branches: [develop,master]
  pull_request:
    branches: [develop,master]

jobs:
  tests:
    name: Execute tests
    runs-on: ubuntu-latest

    env:
      APP_ENV: "test"
      DATABASE_URL: "pgsql://postgres:postgres@localhost:5432/postgres"

    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          ini-values: date.timezone = Europe/Paris

      - name: Composer validate
        run: composer validate

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/composer/files
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install PHP CS fixer
        run: |
          wget https://cs.symfony.com/download/php-cs-fixer-v2.phar -O php-cs-fixer
          sudo chmod a+x php-cs-fixer
          sudo mv php-cs-fixer /usr/local/bin/php-cs-fixer

      - name: Install node modules
        run: |
          yarn install

      - name: Lint
        run: |
          php-cs-fixer fix --diff --dry-run --no-interaction -v
          bin/console lint:yaml config --parse-tags config
          bin/console lint:twig templates --env=prod
          bin/console lint:container

      - name: Verify schema
        run: bin/console doctrine:schema:validate --skip-sync -vvv --no-interaction

      - name: Cache security-checked vulnerabilities db
        uses: actions/cache@v2
        with:
          path: ~/.symfony/cache
          key: security-checker-vulns-db

      - uses: symfonycorp/security-checker-action@v1

      - name: Build assets
        run: |
          yarn build

      - name: Update database
        run: bin/console doctrine:migrations:migrate -n

      - name: Run fixtures
        run: bin/console doctrine:migrations:migrate -n

      - name: Clear the test cache
        run: bin/console cache:clear --env test

      - name: Run test suite
        run: SYMFONY_DEPRECATIONS_HELPER=disabled bin/phpunit
