name: Continuous Integration

on:
    pull_request:
        types:
            - opened
            - reopened
            - synchronize
            - ready_for_review

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest

        if: false == github.event.pull_request.draft

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install PHP
              uses: shivammathur/setup-php@v2
              with:
                  coverage: none
                  php-version: 8.2
                  tools: composer:v2

            - name: Get Composer Cache Directory
              id: composer-cache
              run: echo "cache-dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

            - name: Cache composer
              uses: actions/cache@v3
              with:
                  path: ${{ steps.composer-cache.outputs.cache-dir }}"
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-composer-

            - name: Composer install
              run: composer install --no-interaction --no-progress

            - name: Lint YAML files
              run: ./bin/console lint:yaml config --parse-tags

            - name: Lint Twig templates
              run: ./bin/console lint:twig templates --env=prod

            - name: Lint XLIFF translations
              run: ./bin/console lint:xliff translations

            - name: Lint Parameters and Services
              run: ./bin/console lint:container --no-debug

            - name: Lint Doctrine entities
              run: ./bin/console doctrine:schema:validate --skip-sync -vvv --no-interaction

            - name: Lint Composer config
              run: composer validate

    rector:
        name: Rector
        runs-on: ubuntu-latest

        if: false == github.event.pull_request.draft

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install PHP
              uses: shivammathur/setup-php@v2
              with:
                  coverage: none
                  php-version: 8.2
                  tools: composer:v2

            - name: Get Composer Cache Directory
              id: composer-cache
              run: echo "cache-dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

            - name: Cache composer
              uses: actions/cache@v3
              with:
                  path: ${{ steps.composer-cache.outputs.cache-dir }}"
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-composer-

            - name: Composer install
              run: composer install --no-interaction --no-progress

            - name: Run Rector
              run: ./vendor/bin/rector process --dry-run

    php-cs-fixer:
        name: PHP CS Fixer
        runs-on: ubuntu-latest

        if: false == github.event.pull_request.draft

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install PHP
              uses: shivammathur/setup-php@v2
              with:
                  coverage: none
                  php-version: 8.2
                  tools: composer:v2

            - name: Get Composer Cache Directory
              id: composer-cache
              run: echo "cache-dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

            - name: Cache composer
              uses: actions/cache@v3
              with:
                  path: ${{ steps.composer-cache.outputs.cache-dir }}"
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-composer-

            - name: Composer install
              run: composer install --no-interaction --no-progress

            - name: Run PHP CS Fixer
              run: ./vendor/bin/php-cs-fixer fix --dry-run --diff --no-interaction -v

    phpstan:
        name: PHP Stan
        runs-on: ubuntu-latest

        if: false == github.event.pull_request.draft

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install PHP
              uses: shivammathur/setup-php@v2
              with:
                  coverage: none
                  php-version: 8.2
                  tools: composer:v2

            - name: Get Composer Cache Directory
              id: composer-cache
              run: echo "cache-dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

            - name: Cache composer
              uses: actions/cache@v3
              with:
                  path: ${{ steps.composer-cache.outputs.cache-dir }}"
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-composer-

            - name: Composer install
              run: composer install --no-interaction --no-progress

            - name: PHP Stan
              run: ./vendor/bin/phpstan

    security-checker:
        name: Security Checker
        runs-on: ubuntu-latest

        if: false == github.event.pull_request.draft

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Security checker
              uses: symfonycorp/security-checker-action@v3

    migrations-and-fixtures:
        name: Migrations & Fixtures
        runs-on: ubuntu-latest

        needs: [ lint, rector, php-cs-fixer, phpstan, security-checker ]

        services:
            postgres:
                image: postgres
                env:
                    POSTGRES_USER: app
                    POSTGRES_PASSWORD: "!ChangeMe!"
                    POSTGRES_DB: app
                ports:
                    - 5432:5432
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5

        steps:
            - name: Checkout develop branch code
              uses: actions/checkout@v3
              with:
                  ref: develop

            - name: Install PHP with extensions
              uses: shivammathur/setup-php@v2
              with:
                  coverage: "none"
                  php-version: 8.2
                  tools: composer:v2

            - uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: 'npm'

            - name: Set composer cache directory
              id: composer-cache
              run: echo "cache-dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

            - name: Cache composer
              uses: actions/cache@v3
              with:
                  path: ${{ steps.composer-cache.outputs.cache-dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('composer.json') }}
                  restore-keys: |
                    ${{ runner.os }}-composer-

            - name: Install vendors
              run: composer install --no-interaction --optimize-autoloader

            - name: Set yarn cache directory
              id: yarn-cache
              run: echo "cache-dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

            - name: Cache yarn
              uses: actions/cache@v3
              with:
                path: ${{ steps.yarn-cache.outputs.cache-dir }}
                key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                restore-keys: |
                  ${{ runner.os }}-yarn-

            - name: Install node_modules
              run: yarn install

            - name: Build assets
              run: yarn build

            - name: Apply develop migrations
              run: bin/console doctrine:migrations:migrate --no-interaction

            - name: Load develop fixtures
              run: bin/console doctrine:fixtures:load --no-interaction

            - name: Switch to the PR branch
              run: |
                  git fetch
                  git switch ${{ github.head_ref }}

            - name: Install vendors
              run: composer install --no-interaction --prefer-dist --optimize-autoloader

            - name: Apply migrations
              run: bin/console doctrine:migrations:migrate --no-interaction

            - name: Validate schema
              run: bin/console doctrine:schema:validate -vvv --no-interaction

            - name: Load fixtures
              run: bin/console doctrine:fixtures:load --no-interaction --purge-with-truncate

    tests:
        name: Tests

        needs: [ lint, rector, php-cs-fixer, phpstan, security-checker ]

        uses: ./.github/workflows/tests.yaml
        secrets: inherit
