name: Lint

on:
    push:
        branches: [ main, develop ]
    pull_request:
        types:
            - opened
            - reopened
            - synchronize
            - ready_for_review

jobs:
    security-checker:
        name: Security Checker
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Security checker
              uses: symfonycorp/security-checker-action@v2

    linters:
        name: Linters
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install PHP
              uses: shivammathur/setup-php@v2
              with:
                  coverage: none
                  php-version: '8.1'
                  tools: composer:v2

            - name: Get Composer Cache Directory
              id: composer-cache
              run: |
                  echo "::set-output name=dir::$(composer config cache-files-dir)"

            - uses: actions/cache@v2
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-composer-

            - name: Composer install
              run: composer install --no-interaction --no-progress

            - name: Lint YAML files
              run: ./bin/console lint:yaml config --parse-tags

            - name: Lint Twig templates
              run: ./bin/console lint:twig templates --env=prod

            - name: Lint XLIFF translations
              run: ./bin/console lint:xliff translations

            - name: Lint Parameters and Services
              run: ./bin/console lint:container --no-debug

            - name: Lint Doctrine entities
              run: ./bin/console doctrine:schema:validate --skip-sync -vvv --no-interaction

            - name: Lint Composer config
              run: composer validate

            - name: Run PHP-CS-Fixer
              run: ./vendor/bin/php-cs-fixer fix --dry-run --diff --no-interaction -v

            - name: Run Psalm
              run: ./vendor/bin/psalm
