on:
    workflow_call:
        secrets:
            SONAR_TOKEN:
                required: true

jobs:
    tests:
        name: Tests
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres:15-alpine
                env:
                    POSTGRES_USER: app
                    POSTGRES_PASSWORD: "!ChangeMe!"
                    POSTGRES_DB: app
                ports:
                    - 5432:5432
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install PHP with extensions
              uses: shivammathur/setup-php@v2
              with:
                  coverage: pcov
                  php-version: 8.3
                  tools: composer:v2
                  ini-values: zend.assertions=1

            - name: Install NodeJS
              uses: actions/setup-node@v4
              with:
                  node-version: 18
                  cache: 'npm'

            - name: Get composer cache directory path
              id: composer-cache
              run: |
                  echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

            - name: Composer cache
              uses: actions/cache@v4
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-composer-

            - name: Install vendors
              run: composer install --no-interaction --optimize-autoloader

            - name: Install node_modules
              run: npm ci

            - name: Build assets
              run: npm run build

            - name: Get coverage cache directory path
              id: coverage-cache-dir-path
              run: echo "dir=$(pwd)/.coverage-cache" >> $GITHUB_OUTPUT

            - name: Coverage cache
              uses: actions/cache@v4
              id: coverage-cache
              with:
                  path: ${{ steps.coverage-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-coverage-cache-${{ hashFiles('src', 'templates', 'tests', 'phpunit.xml.dist') }}
                  restore-keys: |
                      ${{ runner.os }}-coverage-cache-

            - name: Run tests
              run: SYMFONY_DEPRECATIONS_HELPER=weak FOUNDRY_RESET_MODE=migrate bin/phpunit --coverage-clover coverage-report.xml --log-junit tests-report.xml

            - name: Upload reports
              uses: actions/upload-artifact@v3
              with:
                  name: reports
                  path: |
                      coverage-report.xml
                      tests-report.xml
                  retention-days: 1

    sonar-cloud:
        name: SonarCloud
        runs-on: ubuntu-latest

        needs: tests

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

            - name: Download Coverage Reports
              uses: actions/download-artifact@v3
              with:
                  name: reports

            - name: Change Paths from PHPUnit reports
              run: |
                  sed -i 's#/home/runner/work/apps/apps#/github/workspace#g' coverage-report.xml

            - name: SonarCloud Scan
              uses: SonarSource/sonarcloud-github-action@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
